apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault-controller
  name: vault-controller
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: vault-controller-cert
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: vault-controller
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: vault-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-controller
    spec:
      containers:
      - name: vault-controller
        image: "vatsakatta/vault-controller:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: VAULTCONTROLLER_VAULT_ROOTTOKEN
          valueFrom:
            secretKeyRef:
              name: vault-controller
              key: vault-token
        - name: VAULTCONTROLLER_VAULT_SCHEME
          value: "http"
        - name: VAULTCONTROLLER_VAULT_HOST
          value: "vault.vault-controller.svc.cluster.local"
        - name: VAULTCONTROLLER_VAULT_PORT
          value: "8200"
        - name: VAULTCONTROLLER_OPENSHIFT_HOST
          value: "openshift.default.svc.cluster.local"
        - name: VAULTCONTROLLER_OPENSHIFT_PORT
          value: "443"
        - name: VAULTCONTROLLER_OPENSHIFT_AUTHTOKEN
          value: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ2YXVsdC1jb250cm9sbGVyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlcGxveWVyLXRva2VuLTN6cHhqIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlcGxveWVyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMTJkMDI3MWMtODM3Zi0xMWU3LWFhYTMtYmUyZjRlYzkwZjI5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnZhdWx0LWNvbnRyb2xsZXI6ZGVwbG95ZXIifQ.l-2bdiPvcTnFO4vS0wQkJMaPIfyUV7QOkknPcMm9-DaZLezkptHHgpGyZG-I5783JPCwaV0Q0405izlXKH7-GQ53m3QGEvy3f2-dPdxgZyaB9qBCZgx2qno1WXC11gXrWxXjsi6agPTg9DJ7vTMNWydwWa3-7O8G_SueO7yuexj6NtXAwLUEcC6TUVmtx8cct5M21G-gi0MEadbETwCS96ccuLvSN39il3Gk8_zy9HZNkBuyPxQAb5k1VCPcVO1ESDhGtb4PoV99Gv7G4dSBdeZ9Fh0x9YKIisiGcSV4Ci0G2UiSA0b_vV7bweFAPGSp70P24yPE1tWc2bene-Zh0g"
        - name: VAULTCONTROLLER_INITCONTAINERPORT
          value: "8443"
        - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_CLIENT
          value: "DEBUG"
        volumeMounts:
        - name: vault-controller-cert
          mountPath: /var/run/secrets/kubernetes.io/certs
      volumes:
      - name: vault-controller-cert
        secret:
          secretName: vault-controller-cert
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-controller
data:
  vault-token: YjNhYjQzNmMtMDgxZi1kZmVkLTA4M2YtNjZkZWNiMDBmYThm

