apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault-springapp
  name: vault-springapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: vault-springapp
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: vault-springapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-springapp
      annotations:
        vaultproject.io/policies: default,vault-springapp
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "token-retriever",
            "image": "vatsakatta/token-retriever:latest",
            "imagePullPolicy": "Always",
            "ports" : [
              {
                "containerPort" : 8443,
                "name" : "init-port",
                "protocol" : "TCP"
               }
            ],
            "env": [
              {
                "name": "APPLICATION_POD_NAME",
                "valueFrom": {"fieldRef": {"fieldPath": "metadata.name", "apiVersion": "v1"}}
              },
              {
                "name": "APPLICATION_POD_IP",
                "valueFrom": {"fieldRef": {"fieldPath": "status.podIP", "apiVersion": "v1"}}
              },
              {
                "name": "APPLICATION_POD_NAMESPACE",
                "valueFrom": {"fieldRef": {"fieldPath": "metadata.namespace", "apiVersion": "v1"}}
              },
              {
                "name": "APPLICATION_VAULT_BASEURI",
                "value": "http://vault:8200"
              },
              {
                "name": "APPLICATION_TOKENFILEPATH",
                "value": "/var/run/secrets/vaultproject.io/token"
              },
              {
                "name": "APPLICATION_VAULTCONTROLLERBASEURI",
                "value": "http://vault-controller:8080"
              }
            ],
            "volumeMounts": [
              {
                "name": "vault-token-vol",
                "mountPath": "/var/run/secrets/vaultproject.io"
              }
            ]
          }
        ]'
    spec:
      containers:
        - name: vault-springapp
          image: "vatsakatta/vault-springapp:latest"
          imagePullPolicy: Always
          env:
          - name: VAULT_HOST
            value: "vault"
          - name: VAULT_PORT
            value: "8200"
          - name: VAULT_SCHEME
            value: "http"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
          volumeMounts:
            - name: vault-token-vol
              mountPath: "/var/run/secrets/vaultproject.io"
      volumes:
        - name: vault-token-vol
          emptyDir:
            medium: Memory
